import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:ristey/assets/error.dart';
import 'package:ristey/assets/g_sign.dart';
import 'package:ristey/common/widgets/social_button.dart';
import 'package:ristey/global_vars.dart';

bool color_done2 = false;

class TCPopup extends StatefulWidget {
final VoidCallback onClick;
  const TCPopup({super.key, required this.onClick});

  @override
  State<TCPopup> createState() => _TCPopupState();
}

class _TCPopupState extends State<TCPopup> {
  String termcondition = "";

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(
        'Terms & Conditions',
        style: TextStyle(color: mainColor),
        textAlign: TextAlign.center,
      ),
      contentPadding:
          const EdgeInsets.only(right: 10, left: 10, bottom: 50, top: 20),
      insetPadding: const EdgeInsets.only(right: 28, left: 28, bottom: 50),
      content: Scrollbar(
        //always show scrollbar
        thickness: 4, //width of scrollbar
        radius: const Radius.circular(20), //corner radius of scrollbar
        scrollbarOrientation: ScrollbarOrientation.right,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            // mainAxisAlignment: MainAxisAlignment.center,
            // crossAxisAlignment: CrossAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Container(
                    // margin: EdgeInsets.only(left:MediaQuery.of(context).size.width*0.01),
                    child: Text(
                      "  FREERISHTEYWALA.COM\n",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                          color: mainColor,
                          fontFamily: "Serif",
                          fontSize: 15,
                          fontWeight: FontWeight.w700),
                    ),
                  ),
                  const Center(
                    child: Text(
                      "Thank You for using \n FREERISHTEYWALA.COM \n ",
                      textAlign: TextAlign.center,
                    ),
                  ),
                ],
              ),

              const Text(
                "FREERISHTEYWALA.COM is a digital Website / Mobile Applications/service provided by SOURABH MEHNDIRATTA THE MATCHMAKER OPC PVT LTD. located at Sco-27 Committee Chowk,Shahabad Markanda Distt. Kurukshetra Haryana,\nIndia PINCODE-136135 \nowns/ operates FREERISHTEYWALA.COM \n(hereinafter referred to as 'Website / Mobile Applications'). \n",
                // textAlign: TextAlign.center,
              ),
              const Text(
                "The Website / Mobile Application provides its users with service which includes but are not limited to Matrimonial cum Dating platforms that allow It’s user to find their partners, chat with people, allows audio and video call, and provides free Kundli Match services.\n",
                // textAlign: TextAlign.center,
              ),
              const Text(
                "Our service and these terms and conditions are compliant with the Information Technology Act, 2000,The Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, and the Indian Contract Act, 1872.\n",
                // textAlign: TextAlign.center,
              ),
              const Text(
                "These terms and conditions outline the rules and regulations for the use of the Website / Mobile Applications. These terms and conditions are a binding agreement between the User of the Website / Mobile Applications and the Website / Mobile Applications and state the terms that govern Your use and access to the Service. Your access or use of the Website / Mobile Applications is subject to these terms and conditions and all applicable laws. By accessing and using the Website / Mobile Applications you accept these terms and conditions without limitation or qualification. Do not continue to use the Website / Mobile Applications if you do not agree to take all of the terms and conditions stated on this page. If, at any time, any part of the terms and conditions is no longer acceptable to you, immediately terminate your  use of the Website / Mobile Applications.\nThis electronic record is prepared in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.\nThis document is published in accordance with the provisions of Rule 3 of the Information Technology (Intermediaries guidelines) Rules, 2021 that require publishing of the rules and regulations, privacy policy, and Terms of Use for access or usage of the Website / Mobile Applications.\nThe following terminology applies to these Terms and Conditions: 'Client', 'You' and 'Your' refers to you, the person using to log in to this Website / Mobile Applications and compliant with the Company’s terms and conditions. 'The Company', 'Ourselves', 'We', 'Our' and 'Us', refers to our Company. 'Party', 'Parties', or 'Us', refers to both the Client and ourselves.\n ",
                // textAlign: TextAlign.center,
              ),
              // Text(
              //   "WHO CAN USE OUR SERVICE ",
              //   textAlign: TextAlign.start,
              //   // textAlign: TextAlign.center,
              //   style: TextStyle(
              //       decoration: TextDecoration.underline,
              //       color: mainColor,
              //       fontFamily: "Serif",
              //       fontSize: 14),
              // ),
              Text(
                "WHO CAN USE OUR SERVICE",
                textAlign: TextAlign.start,
                // textAlign: TextAlign.center,
                style: TextStyle(
                    decoration: TextDecoration.underline,
                    color: mainColor,
                    fontFamily: "Serif",
                    fontSize: 14),
              ),
              const Text(
                  "The services of the Website / Mobile Applications are available only to persons of a specific age. For males, the age is 21 years or above, and for females, the age is 18 years or above. Anyone below the mentioned age is not eligible for the services provided by this Website / Mobile Applications and hence shall not register as a user or transact on this Website / Mobile Applications. \nThe Website / Mobile Applications has the right to access the location of its users. It is important for the Website / Mobile Applications to take access to the location of its user to make sure that it is compliant with local laws. This Website / Mobile Applications is compliant with the laws of India only. Therefore we are not liable for any miss conduct/loss/problem of any users of other regions who access our services using unfair means. \nThe Website / Mobile Applications has the right to terminate your account, wherein the User is found to be defaulting on this condition, or where we find that you are barred in law from access to our Services. \n "),
              Container(
                // margin: EdgeInsets.only(right: 35),
                child: Text(
                  "HOW TO USE OUR SERVICE",
                  style: TextStyle(
                      decoration: TextDecoration.underline,
                      color: mainColor,
                      fontFamily: "Serif",
                      fontSize: 14),
                ),
              ),
              const Text(
                  "We provide you with a free account, however, you are required to be registered with us, to avail full functionalities of our Services. \nTo use our Service, you simply need to run an Website / Mobile Applications on your Mobile Phone (both Android and IOS). \nAs you open our Website / Mobile Applications you are required to register through third-party services such as Google, Facebook, Instagram, LinkedIn, and Twitter. The Website / Mobile Applications has the right to send Mobile Authentication to any user.\nAs you log in to our Website / Mobile Applications we would collect information regarding your device, configuration, internet bandwidth, location, and IP address. The information being collected might increase or decrease from time to time and would be updated and notified to you through our terms and conditions.\nAs Part of the Registration Process for Creating your account, you will need to provide us with your full name, gender, mobile number, religion, Kundli dosh, marital status, diet, drinking habit, smoking habit, diet, height, education, profession, income, about me (optional), about partner preference (optional), six \n(6) photo (optional), two (2) minute video by user to verify profile (optional), and user address (country, state, city, pin code). \nIf the user fails to complete the registration process in full, the Website / Mobile Applications can not be held liable for any results displayed. Additionally, if the user’s intended purpose is not fulfilled or their experience is negatively impacted, the Website / Mobile Applications can not be held responsible for any such outcomes. \n"),
              Container(
                margin: const EdgeInsets.only(right: 87),
                child: Text(
                  "USER SUBMISSIONS",
                  style: TextStyle(
                      decoration: TextDecoration.underline,
                      color: mainColor,
                      fontFamily: "Serif",
                      fontSize: 14),
                ),
              ),
              const Text(
                  "We may provide interactive activities for the Website / Mobile Applications communities which include but are not limited to activities such as free unlimited chat with other users, free unlimited video calls with other users,   free unlimited audio calls with other users, free conference call facility to both the user, etc (collectively, “Interactive Areas”) for the enjoyment of our visitors. You must be of legal age or older to participate in the Website / Mobile Applicationss Interactive Areas.\nWe do not claim ownership of any information, data, text, software, music, sound, photographs, graphics, video, messages, tags, or other materials you submit for display or distribution to others through the Website / Mobile Applications, including any such materials that you submit through Interactive Areas (collectively, 'User Submissions'). As between you and us, you own all rights to your User Submissions. However, you grant (and confirm and promise to us that you have the right to grant) to us and our affiliates, representatives, and sublicensees and assign an irrevocable, perpetual, non-exclusive, sub-licensable, royalty-free and fully-paid, license (sublicensable through multiple tiers) throughout the universe to use, distribute, syndicate, license, reproduce, modify, adapt, publish, translate, publicly perform, create derivate works and publicly display your User Submissions (in whole or in part) in any format or medium now known or later developed; provided, however, that the exercise of our rights under the foregoing license shall at all times be subject to the limitations upon disclosure of your User Submissions imposed on us under our Privacy Notice. You hereby irrevocably waive (and agree to cause to be waived) any claims and assertions of moral rights or attributions with respect to your User Submissions. We reserve the right to display advertisements in connection with User Submissions and to use User Submissions for advertising and promotional purposes without any compensation to you. These advertisements may be targeted at the content or information stored on the Services. In consideration for us granting you access and use of the Services, you agree that we may place such advertisements throughout our Services. We do not pre-screen all User Submissions, and you agree that you are solely responsible for all of your User Submissions. By participating in any of the aforementioned activities, all visitors and members agree to follow the Website / Mobile Applicationss, standards of conduct. Postings to public areas may or may not be reviewed by the Website / Mobile Applications prior to appearing on the Website / Mobile Applications. Nonetheless, the Website / Mobile Applications reserve the right to change, delete or remove, in part or in full, any postings in Interactive Areas and to terminate or suspend access to such areas for conduct that we believe, in our sole discretion, interferes with other peoples’ enjoyment of our Website / Mobile Applications. The Website / Mobile Applications will also cooperate with local, state, and/or federal authorities to comply with applicable law. \nWe are not required to backup, host, display, or distribute any User Submissions, and may remove at any time or refuse any User Submissions. We are not responsible for any loss, theft, or damage of any kind to any User Submissions. You represent and warrant that your User Submissions and our authorized use of such submissions do not and will not infringe the rights of any third party (including, without limitation, intellectual property rights, rights of privacy or publicity, or any other legal or moral rights). Your User Submissions must not violate our policies. You may not represent or imply to others that your User Submissions are in any way provided, sponsored, or endorsed by us. Please consider the risks of revealing personal information (such as name, phone number, or street address) about yourself or others in Interactive Areas, including when connecting to the Sites through a third-party service. You, and not we, are responsible for any consequences of sharing personal information about yourself in public areas of the Service, such as your home address or the home address of others.\nWe own all rights, titles, and interests in any compilation, collective work, or other derivative work created by us using or incorporating your content (but not your original content). When you use a feature on the Services that allows users to share, transform, readapt, modify, or combine user content with other content, you grant us and our users an irrevocable, non-exclusive, royalty-free, perpetual, right and license in the universe to use, reproduce, modify, display, remix, perform, distribute, redistribute, adapt, promote, create derivative works, and syndicate your content in any medium and through any form of technology or distribution and to permit any derivative works to be licensed under these same license terms.\n"),
              Text(
                "USER CONDUCT AND PROHIBITED CONTENT",
                style: TextStyle(
                    decoration: TextDecoration.underline,
                    color: mainColor,
                    fontFamily: "Serif",
                    fontSize: 14),
              ),
              const Text(
                  "Under section 3(b) of Information Technology (Intermediaries guidelines) Rules, 2021 the users shall not host, display, upload, publish, transmit, store, update or share any information or link that belongs to another person and to which the user does not have any right; \n --	is defamatory, obscene, pornographic, paedophilic, invasive of another's privacy, including bodily privacy, insulting or harassing on the basis of gender, libelous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force; \n - Is harmful to children; \n - -	infringes any patent, trademark, copyright, or other proprietary rights; \n --	violates any law for the time being in force; \n - Impersonates other people; \n - -	deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact; \n --	threatens the unity, integrity, defense, security, or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offense or prevents investigation of any offense or is insulting other nation \n --	contains a software virus or any other computer code, file, or program designed to interrupt, destroy or limit the functionality of any computer resource; \n - -	is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity, or agency for financial gain or to cause injury to any person;"),
              const SizedBox(
                height: 20,
              ),
              Container(
                margin: const EdgeInsets.only(right: 52),
                child: Text(
                  "THIRD-PARTY SERVICES",
                  style: TextStyle(
                      decoration: TextDecoration.underline,
                      color: mainColor,
                      fontFamily: "Serif",
                      fontSize: 14),
                ),
              ),
              const Text(
                  "While our Platform is a freely accessible and usable platform, we need to generate revenue so that we can keep offering you our Services for free. Pursuant to this, we may share any data that we may collect including but not limited to your username, profile pictures, your usage and engagement habits, and patterns on our Platform to show you any sponsored content or advertisements. We will not, however, be liable to pay you any revenue share if you purchase any products advertised to you. We do not endorse any products or vouch for the authenticity of the products. Merely advertising products by the users on our Platform does not amount to an endorsement by us. \nPlease note that we do not control such third-party Website / Mobile Applicationss and their interactions with you. We have not reviewed, and do not review, all the material, including goods or services, made available through third-party sites. We, therefore, urge you to kindly make an informed choice in interacting with such third-party sites and ensure that you are familiar with the policies of such sites before you proceed with engaging and interacting, with such third-party sites. \n "),
              Text(
                "INTERMEDIARY STATUS AND NO  LIABILITY",
                style: TextStyle(
                    decoration: TextDecoration.underline,
                    color: mainColor,
                    fontFamily: "Serif",
                    fontSize: 14),
              ),
              const Text(
                  "We are an intermediary as defined under the Information Technology Act, 2000, and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021. These Terms are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 that require publishing of the rules and regulations, the Privacy Policy, and Terms and Conditions for accessing and using our Platform. Our role is limited to providing a platform for users to show the perfect matches for them according to the information collected by the Website / Mobile Applications or information shared by the users to the Website / Mobile Applications. \nWe do not control what you or other people may or may not do on the Platform and are thus, not responsible for the consequences of such actions (whether online or offline). We are not responsible for services and features offered by others, even if you access them through our Services. Our responsibility for anything that happens on our Platform is strictly governed by the laws of India and is limited to that extent. You agree that we will not be responsible for any loss of profits, revenues, information, or data, or consequential, special, indirect, exemplary, punitive, or incidental damages arising to you or any other person related to these Terms, even if we know they are possible. This includes when we delete your content, information, or account. \nWe are an intermediary under Indian law. We do not control what people post on our Platform but we expect everyone to comply with the Content and Community Guidelines. \n"),
              Container(
                margin: const EdgeInsets.only(right: 90),
                child: Text(
                  "INDEMNIFICATION",
                  style: TextStyle(
                      decoration: TextDecoration.underline,
                      color: mainColor,
                      fontFamily: "Serif",
                      fontSize: 14),
                ),
              ),
              const Text(
                  "You agree to fully indemnify, defend and hold harmless the Website / Mobile Applications, its affiliates, associates, and group companies, and their respective directors, key managerial personnel, employees, officers, shareholders, agents, representatives, sub-contractors, consultants, and third-party providers from and against all losses, claims, and damages including legal fees, resulting from (i) Your violation of any terms of the terms and conditions; (iii) Your violation of any third party right, including without limitation any publicity, privacy, or intellectual property right; (iv) Your breach of any applicable laws; (iv) any unauthorized, improper, illegal or wrongful use of Your account by any person, including a third party, whether or not authorized or permitted by You; and (v) Your breach of any representation, warranty, covenant or undertaking under the User Agreement or under applicable law. This indemnification obligation will survive the expiry or termination of these terms and conditions and Your use of the service. \n"),
              Container(
                margin: const EdgeInsets.only(right: 100),
                child: Text(
                  "GOVERNING LAW",
                  style: TextStyle(
                      decoration: TextDecoration.underline,
                      color: mainColor,
                      fontFamily: "Serif",
                      fontSize: 14),
                ),
              ),
              const Text(
                  "This Agreement shall be governed by and construed in accordance with the laws of India provided the Website / Mobile Applications is available and operated under a locally registered legal entity in India, without regard to the conflict of laws provisions thereof. All claims, differences, and disputes arising under or in connection with or in relation hereto the Website / Mobile Applications or Services, the Terms or any transactions entered into on or through the Website / Mobile Applications or Services shall be subject to the exclusive jurisdiction of the courts at Haryana, India and You hereby accede to and accept the jurisdiction of such courts."),
              const SizedBox(
                height: 20,
              ),

              Container(
                margin: const EdgeInsets.only(right: 65),
                child: Text(
                  "DISPUTE RESOLUTION",
                  style: TextStyle(
                      decoration: TextDecoration.underline,
                      color: mainColor,
                      fontFamily: "Serif",
                      fontSize: 14),
                ),
              ),
              const Text(
                  "Any and all disputes arising or related to these terms and conditions shall be settled according to the Arbitration Rules of the Arbitration Court at the International Chamber of Commerce by a sole arbitrator who shall be decided mutually by the parties. The arbitration proceeding shall take place in Haryana in English language only. The parties hereby declare that a decision made as a result of the arbitration proceeding shall be bounding for both parties. \nIf both parties are not satisfied with the arbitration result then the parties have the right to move to the high court of Punjab and Haryana \n \n"),

              // CustomSpecialButtom(
              //     shadowColor:
              //         MaterialStateColor.resolveWith((states) => Colors.black),
              //     // shadowcolor: Colors.red,
              //     text: "Agree",
              //     bordercolor: Colors.black,
              //     button_pressed: () {
              //       Navigator.of(context).push(
              //           MaterialPageRoute(builder: (builder) => SignInScreen()));
              //     })
              Center(
                child: Container(
                  margin: const EdgeInsets.only(left: 6),
                  width: MediaQuery.of(context).size.width * 0.6,
                  child: ElevatedButton(
                      style: ButtonStyle(
                          shadowColor: WidgetStateColor.resolveWith(
                              (states) => Colors.black),
                          padding: WidgetStateProperty.all<EdgeInsetsGeometry?>(
                              const EdgeInsets.symmetric(vertical: 17)),
                          shape:
                              WidgetStateProperty.all<RoundedRectangleBorder>(
                                  RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(60.0),
                                      side: BorderSide(
                                        color: (color_done2 == false)
                                            ? Colors.white
                                            : mainColor,
                                      ))),
                          backgroundColor:
                              WidgetStateProperty.all<Color>(Colors.white)),
                      onPressed: () {
                        setState(() {
                          color_done2 = true;
                        });
widget.onClick();
                        // Get.dialog(Dialog(
                        //   insetPadding:
                        //       const EdgeInsets.symmetric(horizontal: 15),
                        //   shape: RoundedRectangleBorder(
                        //       borderRadius: BorderRadius.circular(30)),
                        //   elevation: 3,
                        //   child: Padding(
                        //     padding: const EdgeInsets.symmetric(
                        //         horizontal: 15, vertical: 30),
                        //     child: Column(
                        //       mainAxisSize: MainAxisSize.min,
                        //       children: [
                        //         InkWell(
                        //             onTap: () {
                        //               signup(context);
                        //             },
                        //             child: const SocialButton(
                        //                 image: "images/google.png",
                        //                 name: "Continue With Google")),
                        //         InkWell(
                        //           onTap: () {
                        //             showDialog(
                        //                 barrierDismissible: false,
                        //                 context: context,
                        //                 builder: (context) {
                        //                   return const AlertDialog(
                        //                     content: SnackBarContent(
                        //                       error_text:
                        //                           "Please Continue With Google",
                        //                       appreciation: "",
                        //                       icon: Icons.error,
                        //                       sec: 2,
                        //                     ),
                        //                     backgroundColor: Colors.transparent,
                        //                     elevation: 0,
                        //                   );
                        //                 });
                        //           },
                        //           child: const SocialButton(
                        //               image: "images/facebook.png",
                        //               name: "Continue With Facebook"),
                        //         ),
                        //         InkWell(
                        //           onTap: () {
                        //             showDialog(
                        //                 barrierDismissible: false,
                        //                 context: context,
                        //                 builder: (context) {
                        //                   return const AlertDialog(
                        //                     content: SnackBarContent(
                        //                       error_text:
                        //                           "Please Continue With Google",
                        //                       appreciation: "",
                        //                       icon: Icons.error,
                        //                       sec: 2,
                        //                     ),
                        //                     backgroundColor: Colors.transparent,
                        //                     elevation: 0,
                        //                   );
                        //                 });
                        //           },
                        //           child: const SocialButton(
                        //               image: "images/instagram.png",
                        //               name: "Continue With Instagram"),
                        //         ),
                        //         InkWell(
                        //           onTap: () {
                        //             showDialog(
                        //                 barrierDismissible: false,
                        //                 context: context,
                        //                 builder: (context) {
                        //                   return const AlertDialog(
                        //                     content: SnackBarContent(
                        //                       error_text:
                        //                           "Please Continue With Google",
                        //                       appreciation: "",
                        //                       icon: Icons.error,
                        //                       sec: 2,
                        //                     ),
                        //                     backgroundColor: Colors.transparent,
                        //                     elevation: 0,
                        //                   );
                        //                 });
                        //           },
                        //           child: const SocialButton(
                        //               image: "images/twitter.png",
                        //               name: "Continue With Twitter"),
                        //         ),
                        //         InkWell(
                        //           onTap: () {
                        //             showDialog(
                        //                 barrierDismissible: false,
                        //                 context: context,
                        //                 builder: (context) {
                        //                   return const AlertDialog(
                        //                     content: SnackBarContent(
                        //                       error_text:
                        //                           "Please Continue With Google",
                        //                       appreciation: "",
                        //                       icon: Icons.error,
                        //                       sec: 2,
                        //                     ),
                        //                     backgroundColor: Colors.transparent,
                        //                     elevation: 0,
                        //                   );
                        //                 });
                        //           },
                        //           child: const SocialButton(
                        //               image: "images/linkedin.png",
                        //               name: "Continue With Linkedin"),
                        //         ),
                        //       ],
                        //     ),
                        //   ),
                        // ));
                      },
                      child: Text(
                        "Agree",
                        style: (color_done2 == false)
                            ? const TextStyle(
                                color: Colors.black,
                                fontSize: 20,
                                fontFamily: 'Serif',
                                fontWeight: FontWeight.w700)
                            : TextStyle(
                                color: mainColor,
                                fontSize: 20,
                                fontFamily: 'Serif',
                                fontWeight: FontWeight.w700),
                      )),
                ),
              ),
              const SizedBox(
                height: 12,
              )
            ],
          ),
        ),
      ),
      actions: <Widget>[
        TextButton(
          onPressed: () {
            Navigator.of(context).pop();
          },
          child: Text(
            'Close',
            style: TextStyle(color: mainColor),
          ),
        ),
      ],
    );
  }
}
